### ISSUE TITLE
error when running plugin in pycharm

### ISSUE THREAD

**Issue by mellahysf** [neulab/tranX-plugin#25]
Hi,

After installation of the tranX plugin, and when i tiped the intent and click Go! it gives me the folowing error : 
Caught exception: java.util.concurrent.ExecutionException: com.jayway.jsonpath.PathNotFoundException: Missing property in path $['items']

what's the problem ?

**Comment by frankxu2004** [comment]
I think it might be related to Internet connection, since the plugin needs to access our server, Bing and StackOverflow to perform correctly. Could you access something like https://api.stackexchange.com/2.2/questions/?site=stackoverflow?
